export enum Permission {
  ADMIN = "admin",
  VIEW_ANIME = "view anime",
  ADD_ANIME = "add anime",
  EDIT_ANIME = "edit anime",
  REMOVE_FROM_CURRENT = "remove from current",
  DELETE_ANIME = "delete anime",
  VIEW_ALL_USERS = "view all users",
  ADD_USERS = "add users",
  EDIT_USERS = "edit users",
  DELETE_USERS = "delete users",
  VOTE = "vote",
  GRANT_VOTES = "grant votes",
  DELETE_VOTES = "delete votes",
  CHANGE_EPISODE = "change episode",
  CHANGE_CONTINUING_SERIES = "change cs",
  GRANT_PERMISSIONS = "grant permissions",
  VIEW_ADMIN = "view admin dashboard",
  SEND_NOTIFICATIONS = "send notification",
}
